[alembic]
# Path to the Alembic configuration directory
script_location = alembic

# The sqlalchemy.url is overridden in env.py to support async engines.
# This placeholder prevents Alembic from complaining.
sqlalchemy.url = postgresql+asyncpg://postgres:Dbs171920@localhost:5432/ClarkPlayer

# Logging
file_template = %%(year)d-%%(month).2d-%%(day).2d %%(rev)s %%(slug)s [%%(author)s]
