"""
Massive catalog seed data — 5000+ artists across 40+ genres.

Designed for Phase 1 expansion of ClarkPlayer catalog.
Each list targets popular artists with available preview URLs (iTunes).
Genres are organized in priority order for batch ingestion.
"""

from __future__ import annotations

# ── Phase 1 Core: 5000+ artists organised by genre ─────────────────────

MASSIVE_SEED: dict[str, list[str]] = {
    # ═══════════════════════════════════════════════════════════════════
    # MAJOR GENRES (100+ artists each)
    # ═══════════════════════════════════════════════════════════════════

    "pop": [
        # A-list global
        "Taylor Swift", "Ed Sheeran", "Ariana Grande", "Bruno Mars",
        "Dua Lipa", "Harry Styles", "Billie Eilish", "Justin Bieber",
        "Lady Gaga", "The Weeknd", "SZA", "Olivia Rodrigo",
        "Miley Cyrus", "Shawn Mendes", "Katy Perry", "Rihanna",
        "Sam Smith", "Sia", "Charlie Puth", "Selena Gomez",
        "Camila Cabello", "Demi Lovato", "Halsey", "Lizzo",
        "Doja Cat", "Pink", "Maroon 5", "Adele",
        "Lana Del Rey", "Sabrina Carpenter", "Chappell Roan", "Tate McRae",
        "Benson Boone", "Teddy Swims", "Gracie Abrams", "Conan Gray",
        "Niall Horan", "Zayn", "Louis Tomlinson", "Liam Payne",
        "One Direction", "Jonas Brothers", "5 Seconds of Summer",
        "Carly Rae Jepsen", "Charli XCX", "Troye Sivan", "Lorde",
        "Ava Max", "Bebe Rexha", "Anne-Marie", "Rita Ora",
        "Ellie Goulding", "Jessie J", "Meghan Trainor", "Jason Derulo",
        "Taio Cruz", "Flo Rida", "Pitbull", "will.i.am",
        "Pharrell Williams", "Justin Timberlake", "Robin Thicke",
        "John Legend", "Alessia Cara", "Tori Kelly", "Julia Michaels",
        "Hailee Steinfeld", "Zara Larsson", "Becky G", "Anitta",
        # K-pop crossover
        "BTS", "BLACKPINK", "Jung Kook", "Jimin", "Lisa", "Rosé",
        "TWICE", "Stray Kids", "NewJeans", "Fifty Fifty",
        # Latin pop crossover
        "Shakira", "Enrique Iglesias", "Ricky Martin",
        "Jennifer Lopez", "Marc Anthony", "Luis Fonsi",
        # J-pop
        "YOASOBI", "Kenshi Yonezu", "Official HIGE DANdism",
        "LiSA", "Aimer", "Eve",
        # Classics
        "Michael Jackson", "Madonna", "Whitney Houston", "Prince",
        "George Michael", "Elton John", "Billy Joel", "Phil Collins",
        "Celine Dion", "Mariah Carey", "Janet Jackson", "Britney Spears",
        "Christina Aguilera", "Backstreet Boys", "NSYNC", "Spice Girls",
        "Destiny's Child", "Beyoncé", "Kylie Minogue", "Robbie Williams",
        "Cher", "Tina Turner", "Diana Ross", "Donna Summer",
    ],

    "rock": [
        "Queen", "Nirvana", "Led Zeppelin", "AC/DC",
        "Pink Floyd", "Foo Fighters", "The Beatles", "Red Hot Chili Peppers",
        "U2", "Green Day", "Linkin Park", "Coldplay",
        "Arctic Monkeys", "Radiohead", "The Killers", "Muse",
        "The Strokes", "Oasis", "Weezer", "Pearl Jam",
        "Bon Jovi", "Journey", "Guns N' Roses", "Metallica",
        "Aerosmith", "The Rolling Stones", "The Who", "Eagles",
        "Bruce Springsteen", "Tom Petty", "Fleetwood Mac",
        "David Bowie", "The Police", "The Clash", "Ramones",
        "Blink-182", "Sum 41", "The Offspring", "Weezer",
        "Kings of Leon", "The Black Keys", "Jack White",
        "Imagine Dragons", "Twenty One Pilots", "Fall Out Boy",
        "Panic At The Disco", "My Chemical Romance", "Paramore",
        "Three Days Grace", "Breaking Benjamin", "Shinedown",
        "Godsmack", "Seether", "Theory of a Deadman", "Nickelback",
        "Creed", "Staind", "Bush", "Stone Temple Pilots",
        "Soundgarden", "Alice in Chains", "Pearl Jam",
        "Creedence Clearwater Revival", "Lynyrd Skynyrd",
        "ZZ Top", "Def Leppard", "Mötley Crüe", "Poison",
        "Kiss", "Deep Purple", "Rush", "Yes",
        "Genesis", "Peter Gabriel", "Sting", "Eric Clapton",
        "Jeff Beck", "Jimi Hendrix", "Santana", "Steve Miller Band",
        "Boston", "Foreigner", "REO Speedwagon", "Styx", "Kansas",
        "Heart", "Pat Benatar", "Joan Jett", "Blondie",
        "Dire Straits", "Supertramp", "Electric Light Orchestra",
        "Toto", "Chicago", "The Doobie Brothers",
        "The Cure", "Depeche Mode", "New Order", "Joy Division",
        "The Smiths", "R.E.M.", "Pixies", "Sonic Youth",
        "Smashing Pumpkins", "Jane's Addiction", "Garbage",
        "Weezer", "Incubus", "311", "Sublime",
        "Third Eye Blind", "Matchbox Twenty", "Counting Crows",
        "Goo Goo Dolls", "Collective Soul", "Live",
    ],

    "hip_hop": [
        "Kendrick Lamar", "Drake", "J. Cole", "Travis Scott",
        "Kanye West", "Eminem", "Jay-Z", "Lil Wayne",
        "Nicki Minaj", "Cardi B", "Megan Thee Stallion", "Tyler the Creator",
        "21 Savage", "Future", "Post Malone", "Kid Cudi",
        "A$AP Rocky", "Mac Miller", "Lil Baby", "Jack Harlow",
        "Metro Boomin", "Playboi Carti", "Juice WRLD", "Pop Smoke",
        "Lil Nas X", "Doja Cat", "Lizzo", "Chance the Rapper",
        "Wiz Khalifa", "2 Chainz", "Gucci Mane", "Rick Ross",
        "Pusha T", "Big Sean", "Meek Mill", "YG",
        "Schoolboy Q", "Danny Brown", "Earl Sweatshirt", "Vince Staples",
        "Run the Jewels", "Denzel Curry", "JID", "EarthGang",
        "Nas", "The Notorious B.I.G.", "Tupac", "Wu-Tang Clan",
        "Mobb Deep", "A Tribe Called Quest", "De La Soul",
        "OutKast", "UGK", "Three 6 Mafia", "Bone Thugs-N-Harmony",
        "Snoop Dogg", "Dr. Dre", "Ice Cube", "N.W.A",
        "Eazy-E", "Cypress Hill", "The Roots", "Common",
        "Mos Def", "Talib Kweli", "Lupe Fiasco", "Pharoahe Monch",
        "50 Cent", "The Game", "Ludacris", "T.I.",
        "Young Jeezy", "Jeezy", "Nelly", "Lil Jon",
        "Missy Elliott", "Lauryn Hill", "Queen Latifah", "Salt-N-Pepa",
        "Busta Rhymes", "DMX", "Ja Rule", "Fat Joe",
        "Ghostface Killah", "Method Man", "Redman", "Raekwon",
        "Migos", "Offset", "Quavo", "Roddy Ricch",
        "DaBaby", "Gunna", "Young Thug", "Lil Uzi Vert",
        "NBA YoungBoy", "King Von", "Polo G", "Lil Durk",
        "NLE Choppa", "Blueface", "City Girls", "Saweetie",
        "Coi Leray", "BIA", "Flo Milli", "Latto",
    ],

    "r_and_b": [
        "Beyoncé", "Frank Ocean", "Usher", "Chris Brown",
        "Alicia Keys", "John Legend", "Daniel Caesar", "H.E.R.",
        "Summer Walker", "Jhené Aiko", "Bryson Tiller", "6LACK",
        "Toni Braxton", "Mariah Carey", "Whitney Houston", "Luther Vandross",
        "Miguel", "Snoh Aalegra", "Brent Faiyaz", "PartyNextDoor",
        "Khalid", "Giveon", "Ari Lennox", "Jazmine Sullivan",
        "Lucky Daye", "SiR", "dvsn", "Majid Jordan",
        "Ty Dolla $ign", "Jeremih", "Trey Songz", "August Alsina",
        "Jacquees", "Tank", "Dwele", "Musiq Soulchild",
        "Maxwell", "D'Angelo", "Erykah Badu", "Jill Scott",
        "India.Arie", "Angie Stone", "Floetry", "Heather Headley",
        "Boyz II Men", "New Edition", "Jodeci", "Dru Hill",
        "112", "Jagged Edge", "Blackstreet", "Shai",
        "SWV", "En Vogue", "Xscape", "TLC",
        "Destiny's Child", "Mary J. Blige", "Aaliyah", "Brandy",
        "Monica", "Tamia", "Deborah Cox", "Faith Evans",
        "K-Ci & JoJo", "Next", "Ginuwine", "R. Kelly",
        "Donell Jones", "Case", "Jon B.", "Joe",
        "Mario", "Omarion", "Ne-Yo", "Lloyd",
        "The-Dream", "T-Pain", "Akon", "Sean Paul",
    ],

    "electronic": [
        "Calvin Harris", "David Guetta", "Martin Garrix", "Skrillex",
        "Tiësto", "Deadmau5", "Avicii", "Zedd",
        "Disclosure", "ODESZA", "Flume", "Marshmello",
        "Illenium", "Kygo", "Swedish House Mafia", "Diplo",
        "The Chainsmokers", "Rufus Du Sol", "Jamie xx", "Four Tet",
        "Bonobo", "Caribou", "Floating Points", "Jon Hopkins",
        "Aphex Twin", "Boards of Canada", "Squarepusher", "Autechre",
        "Daft Punk", "Justice", "Kavinsky", "Madeon",
        "Porter Robinson", "Virtual Self", "San Holo", "Said the Sky",
        "Seven Lions", "Above & Beyond", "Armin van Buuren",
        "Paul van Dyk", "Ferry Corsten", "ATB", "Chicane",
        "Robert Miles", "Moby", "The Prodigy", "Fatboy Slim",
        "The Chemical Brothers", "Basement Jaxx", "Groove Armada",
        "Underworld", "Orbital", "Leftfield", "Faithless",
        "Eric Prydz", "Pryda", "Cirez D", "Adam Beyer",
        "Carl Cox", "Richie Hawtin", "Sven Väth", "Paul Kalkbrenner",
        "Boris Brejcha", "Solomun", "Tale Of Us", "Âme",
        "Dixon", "Maceo Plex", "Stephan Bodzin", "Ben Böhmer",
        "Lane 8", "Yotto", "Joris Voorn", "Kölsch",
        "CamelPhat", "Gorgon City", "Chris Lake", "Fisher",
        "Dom Dolla", "John Summit", "Green Velvet", "Claude VonStroke",
        "MK", "Duke Dumont", "Disclosure", "Rudimental",
        "Sigma", "Netsky", "Sub Focus", "Wilkinson",
        "Pendulum", "Chase & Status", "Hybrid Minds", "Dimension",
        "Metrik", "Camo & Krooked", "Fred V & Grafix",
        "Peggy Gou", "Charlotte de Witte", "Amelie Lens",
        "Nina Kraviz", "Helena Hauff", "Ellen Allien",
        "Rezz", "Alison Wonderland", "Tokimonsta", "CloZee",
    ],

    "country": [
        "Luke Combs", "Morgan Wallen", "Chris Stapleton", "Zach Bryan",
        "Kacey Musgraves", "Carrie Underwood", "Tim McGraw", "Blake Shelton",
        "Keith Urban", "Dolly Parton", "Willie Nelson", "Johnny Cash",
        "Garth Brooks", "George Strait", "Carly Pearce", "Dan + Shay",
        "Thomas Rhett", "Kane Brown", "Lainey Wilson", "Bailey Zimmerman",
        "Jason Aldean", "Luke Bryan", "Dierks Bentley", "Brad Paisley",
        "Kenny Chesney", "Toby Keith", "Alan Jackson", "Brooks & Dunn",
        "Reba McEntire", "Martina McBride", "Faith Hill", "Shania Twain",
        "Miranda Lambert", "Lee Ann Womack", "Trisha Yearwood",
        "Dixie Chicks", "The Chicks", "Sugarland", "Lady A",
        "Little Big Town", "Zac Brown Band", "Rascal Flatts",
        "Vince Gill", "Travis Tritt", "Dwight Yoakam", "Hank Williams",
        "Hank Williams Jr.", "Waylon Jennings", "Merle Haggard",
        "Patsy Cline", "Tammy Wynette", "Loretta Lynn", "Conway Twitty",
        "George Jones", "Charley Pride", "Glen Campbell", "Roy Acuff",
        "Ernest Tubb", "Buck Owens", "John Denver", "Jim Reeves",
        "Marty Robbins", "Don Williams", "Eddy Arnold", "Bill Monroe",
        "Alison Krauss", "Rhonda Vincent", "Ricky Skaggs",
        "Sam Hunt", "Devin Dawson", "Jordan Davis", "Michael Ray",
        "Russell Dickerson", "Brett Young", "Cole Swindell",
        "Dustin Lynch", "Chris Young", "Lee Brice", "Justin Moore",
        "Easton Corbin", "Darius Rucker", "Mickey Guyton", "Jimmie Allen",
    ],

    # ═══════════════════════════════════════════════════════════════════
    # SECONDARY GENRES (50-80 artists each)
    # ═══════════════════════════════════════════════════════════════════

    "jazz": [
        "Miles Davis", "John Coltrane", "Billie Holiday", "Duke Ellington",
        "Herbie Hancock", "Thelonious Monk", "Charlie Parker", "Ella Fitzgerald",
        "Dave Brubeck", "Louis Armstrong", "Oscar Peterson", "Chet Baker",
        "Kamasi Washington", "Robert Glasper", "Esperanza Spalding", "Charles Mingus",
        "Nina Simone", "Sonny Rollins", "Wayne Shorter", "Pat Metheny",
        "Diana Krall", "Norah Jones", "Gregory Porter", "Jamie Cullum",
        "Melody Gardot", "Madeleine Peyroux", "Jane Monheit", "Stacey Kent",
        "Branford Marsalis", "Wynton Marsalis", "Christian McBride",
        "Joshua Redman", "Chris Potter", "Brad Mehldau", "Keith Jarrett",
        "Chick Corea", "McCoy Tyner", "Bill Evans", "Art Tatum",
        "Bud Powell", "Count Basie", "Benny Goodman", "Artie Shaw",
        "Dizzy Gillespie", "Clifford Brown", "Lee Morgan", "Freddie Hubbard",
        "Coleman Hawkins", "Lester Young", "Ben Webster", "Stan Getz",
        "Dexter Gordon", "Hank Mobley", "Joe Henderson", "Wayne Shorter",
        "Art Blakey", "Max Roach", "Elvin Jones", "Tony Williams",
        "Roy Haynes", "Jimmy Cobb", "Philly Joe Jones", "Buddy Rich",
        "Ron Carter", "Paul Chambers", "Ray Brown", "Charlie Haden",
        "Jaco Pastorius", "Stanley Clarke", "Victor Wooten", "Marcus Miller",
    ],

    "classical": [
        "Ludovico Einaudi", "Max Richter", "Olafur Arnalds", "Nils Frahm",
        "Johann Sebastian Bach", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart",
        "Frédéric Chopin", "Pyotr Ilyich Tchaikovsky", "Claude Debussy",
        "Antonio Vivaldi", "Yo-Yo Ma", "André Rieu", "Lang Lang",
        "John Williams", "Hans Zimmer", "Alexandre Desplat", "Ennio Morricone",
        "Danny Elfman", "Howard Shore", "James Horner", "Thomas Newman",
        "Philip Glass", "Steve Reich", "John Adams", "Arvo Pärt",
        "Gustav Mahler", "Dmitri Shostakovich", "Sergei Rachmaninoff",
        "Igor Stravinsky", "Maurice Ravel", "Erik Satie", "Camille Saint-Saëns",
        "Franz Schubert", "Robert Schumann", "Johannes Brahms", "Richard Wagner",
        "Giuseppe Verdi", "Giacomo Puccini", "Georges Bizet", "Hector Berlioz",
        "Franz Liszt", "Felix Mendelssohn", "Joseph Haydn", "George Frideric Handel",
        "Henry Purcell", "Claudio Monteverdi", "Thomas Tallis", "William Byrd",
        "Hilary Hahn", "Itzhak Perlman", "Joshua Bell", "Anne-Sophie Mutter",
        "Martha Argerich", "Vladimir Horowitz", "Arthur Rubinstein", "Glenn Gould",
        "Khatia Buniatishvili", "Yuja Wang", "Daniil Trifonov", "Víkingur Ólafsson",
        "Gautier Capuçon", "Sol Gabetta", "Alisa Weilerstein", "Sheku Kanneh-Mason",
    ],

    "latin": [
        "Bad Bunny", "Shakira", "J Balvin", "Rosalía",
        "Karol G", "Daddy Yankee", "Ozuna", "Rauw Alejandro",
        "Maluma", "Anitta", "Luis Fonsi", "Marc Anthony",
        "Romeo Santos", "Feid", "Nicky Jam", "Manuel Turizo",
        "Becky G", "Enrique Iglesias", "Sech", "Luis Miguel",
        "Soda Stereo", "Gustavo Cerati", "Andrés Calamaro", "Fito Páez",
        "Juanes", "Carlos Vives", "Juan Luis Guerra", "Alejandro Sanz",
        "David Bisbal", "Pablo Alborán", "Maná", "Café Tacvba",
        "Natalia Lafourcade", "Mon Laferte", "Julieta Venegas",
        "Ximena Sariñana", "Carla Morrison", "Jesse & Joy",
        "Reik", "Camila", "Sin Bandera", "Ha*Ash",
        "Ricardo Arjona", "Chayanne", "Franco De Vita", "Ricardo Montaner",
        "Luis Miguel", "José José", "Rocío Dúrcal", "Juan Gabriel",
        "Vicente Fernández", "Alejandro Fernández", "Pepe Aguilar",
        "Marco Antonio Solís", "Ana Gabriel", "Los Tigres del Norte",
        "Emmanuel", "Mijares", "Yuri", "Lupita D'Alessio",
        "Myke Towers", "Anuel AA", "Arcángel", "Farruko",
        "Darell", "Jhayco", "Eladio Carrión", "Mora",
        "Quevedo", "Bizarrap", "Duki", "Tiago PZK",
        "Trueno", "Nicki Nicole", "María Becerra", "Emilia",
        "Camilo", "Sebastián Yatra", "Greeicy", "Mike Bahía",
    ],

    "metal": [
        "Metallica", "Iron Maiden", "Black Sabbath", "Slayer",
        "Megadeth", "Pantera", "Tool", "System of a Down",
        "Slipknot", "Avenged Sevenfold", "Rammstein", "Disturbed",
        "Lamb of God", "Mastodon", "Gojira", "Opeth",
        "Korn", "Deftones", "Bring Me the Horizon", "Ghost",
        "Judas Priest", "Motörhead", "Dio", "Ozzy Osbourne",
        "Sepultura", "Meshuggah", "Trivium", "Killswitch Engage",
        "Arch Enemy", "Amon Amarth", "Behemoth", "Dimmu Borgir",
        "Children of Bodom", "In Flames", "At the Gates", "Dark Tranquillity",
        "Soilwork", "Scar Symmetry", "Disarmonia Mundi", "Insomnium",
        "Agalloch", "Wolves in the Throne Room", "Alcest", "Deafheaven",
        "Between the Buried and Me", "Protest the Hero", "Periphery",
        "Animals as Leaders", "Tesseract", "Monuments", "ERRA",
        "Veil of Maya", "Born of Osiris", "After the Burial",
        "Cannibal Corpse", "Death", "Obituary", "Morbid Angel",
        "Carcass", "Napalm Death", "Bolt Thrower", "Entombed",
        "Dismember", "Unleashed", "Grave", "Bloodbath",
        "Katatonia", "My Dying Bride", "Paradise Lost", "Anathema",
        "Type O Negative", "Tiamat", "Moonspell", "The Gathering",
        "Nightwish", "Epica", "Within Temptation", "Lacuna Coil",
        "Sirenia", "Leaves' Eyes", "Amaranthe", "Beyond the Black",
    ],

    "indie": [
        "Mac DeMarco", "Tame Impala", "Vampire Weekend", "Fleet Foxes",
        "Bon Iver", "Beach House", "Phoenix", "MGMT",
        "Arcade Fire", "The xx", "Alt-J", "Glass Animals",
        "Boygenius", "Japanese Breakfast", "Big Thief", "Phoebe Bridgers",
        "Sufjan Stevens", "The National", "Modest Mouse", "Death Cab for Cutie",
        "Neutral Milk Hotel", "Bright Eyes", "Elliott Smith", "Iron & Wine",
        "Band of Horses", "My Morning Jacket", "Wilco", "Built to Spill",
        "Pavement", "Dinosaur Jr.", "Yo La Tengo", "Guided by Voices",
        "Belle and Sebastian", "Camera Obscura", "Alvvays", "Snail Mail",
        "Soccer Mommy", "Lucy Dacus", "Julien Baker", "Courtney Barnett",
        "Mitski", "Weyes Blood", "Angel Olsen", "Sharon Van Etten",
        "Car Seat Headrest", "Black Country New Road", "Squid", "black midi",
        "Dry Cleaning", "Fontaines D.C.", "IDLES", "Shame",
        "King Gizzard & The Lizard Wizard", "Tropical Fuck Storm",
        "Pond", "Unknown Mortal Orchestra", "Toro y Moi", "Washed Out",
        "Neon Indian", "Youth Lagoon", "Deerhunter", "Atlas Sound",
        "Grizzly Bear", "Department of Eagles", "Dirty Projectors",
        "TV on the Radio", "The Walkmen", "Interpol", "Editors",
        "Bloc Party", "Franz Ferdinand", "Arctic Monkeys",
        "The Last Shadow Puppets", "The Libertines", "Babyshambles",
        "The Coral", "The Zutons", "The Kooks", "Razorlight",
    ],

    "blues": [
        "B.B. King", "Muddy Waters", "Robert Johnson", "John Lee Hooker",
        "Buddy Guy", "Stevie Ray Vaughan", "Eric Clapton", "Howlin' Wolf",
        "Gary Clark Jr.", "Joe Bonamassa", "Taj Mahal", "Albert King",
        "Etta James", "Lead Belly", "Keb' Mo'", "Susan Tedeschi",
        "Bonnie Raitt", "Albert Collins", "Freddie King", "Sonny Boy Williamson",
        "T-Bone Walker", "Lightnin' Hopkins", "Elmore James", "Otis Rush",
        "Magic Sam", "Junior Wells", "James Cotton", "Carey Bell",
        "Little Walter", "Big Walter Horton", "Sonny Terry", "Brownie McGhee",
        "Willie Dixon", "Memphis Slim", "Otis Spann", "Pinetop Perkins",
        "Mississippi John Hurt", "Blind Willie McTell", "Reverend Gary Davis",
        "Mississippi Fred McDowell", "Bukka White", "Skip James",
        "Son House", "Charley Patton", "Tommy Johnson", "Blind Lemon Jefferson",
        "Big Bill Broonzy", "Lonnie Johnson", "Scrapper Blackwell",
        "Jimmie Vaughan", "The Fabulous Thunderbirds", "Robert Cray",
        "John Mayer", "Derek Trucks", "Warren Haynes", "Johnny Winter",
        "Kenny Wayne Shepherd", "Jonny Lang", "Samantha Fish", "Ana Popovic",
        "Tab Benoit", "Sonny Landreth", "Luther Allison", "Koko Taylor",
    ],

    "reggae": [
        "Bob Marley", "Peter Tosh", "Jimmy Cliff", "Toots and the Maytals",
        "Steel Pulse", "Damian Marley", "UB40", "Lee Scratch Perry",
        "Burning Spear", "Ziggy Marley", "Dennis Brown", "Gregory Isaacs",
        "Buju Banton", "Sizzla", "Chronixx", "Protoje",
        "Beres Hammond", "Barrington Levy", "Yellowman", "Eek-A-Mouse",
        "Shaggy", "Sean Paul", "Capleton", "Beenie Man",
        "Bounty Killer", "Elephant Man", "Spragga Benz", "Lady Saw",
        "Marcia Griffiths", "Judy Mowatt", "Rita Marley", "Sister Nancy",
        "Hepcat", "The Aggrolites", "The Slackers", "The Expanders",
        "Slightly Stoopid", "Rebelution", "Iration", "SOJA",
        "Stick Figure", "Pepper", "The Green", "Tribal Seeds",
        "Groundation", "John Brown's Body", "10 Ft Ganja Plant",
        "Cultura Profética", "Los Cafres", "Gondwana", "Nonpalidece",
        "Alpha Blondy", "Tiken Jah Fakoly", "Ismaël Isaac",
        "Linton Kwesi Johnson", "Misty in Roots", "Aswad", "Macka B",
        "Black Uhuru", "Israel Vibration", "The Abyssinians", "Culture",
        "Morgan Heritage", "Richie Spice", "Luciano", "Anthony B",
    ],

    "gospel": [
        "Kirk Franklin", "CeCe Winans", "Donnie McClurkin", "Tasha Cobbs",
        "Marvin Sapp", "Tamela Mann", "Fred Hammond", "Shirley Caesar",
        "Jonathan McReynolds", "Kierra Sheard", "Maurette Brown Clark",
        "Yolanda Adams", "Lauren Daigle", "Elevation Worship",
        "Hillsong United", "Chris Tomlin", "Maverick City Music", "Bethel Music",
        "Brandon Lake", "Phil Wickham", "Casting Crowns", "MercyMe",
        "Third Day", "TobyMac", "Michael W. Smith", "Amy Grant",
        "Steven Curtis Chapman", "Jeremy Camp", "Matt Redman", "Tim Hughes",
        "Kari Jobe", "Cody Carnes", "Brooke Ligertwood", "Taya Gaukrodger",
        "Israel Houghton", "Tye Tribbett", "William Murphy", "J.J. Hairston",
        "Travis Greene", "Todd Dulaney", "Anthony Brown", "Byron Cage",
        "Hezekiah Walker", "Donald Lawrence", "Kurt Carr", "Ricky Dillard",
        "John P. Kee", "The Clark Sisters", "Commissioned", "The Winans",
        "Bebe & Cece Winans", "BeBe Winans", "Mary Mary", "Out of Eden",
        "Virtue", "Trin-i-tee 5:7", "Men of Standard", "Darwin Hobbs",
        "Andraé Crouch", "Walter Hawkins", "Edwin Hawkins", "James Cleveland",
        "Mahalia Jackson", "Sister Rosetta Tharpe", "Blind Willie Johnson",
        "The Fairfield Four", "The Dixie Hummingbirds", "The Soul Stirrers",
    ],

    "funk": [
        "James Brown", "George Clinton", "Parliament", "Funkadelic",
        "Sly and the Family Stone", "Earth Wind and Fire", "Tower of Power",
        "Prince", "Rick James", "Bootsy Collins", "Cameo",
        "Graham Central Station", "The Meters", "Vulfpeck", "Khruangbin",
        "Thundercat", "Tom Misch", "Jamiroquai", "Cory Wong",
        "Lettuce", "Soulive", "Galactic", "Dumpstaphunk",
        "Orgone", "The Motet", "Turkuaz", "Pigeons Playing Ping Pong",
        "Kool & the Gang", "Ohio Players", "Commodores", "Lakeside",
        "The Gap Band", "Con Funk Shun", "Slave", "Aurra",
        "Zapp", "Roger", "One Way", "Dazz Band",
        "Charles Wright", "Dyke and the Blazers", "Rufus Thomas",
        "Bobby Byrd", "Lyn Collins", "Marva Whitney", "Maceo Parker",
        "Fred Wesley", "The J.B.'s", "Ike & Tina Turner",
        "Betty Davis", "Betty Wright", "Gwen McCrae", "Candi Staton",
        "Chaka Khan", "Rufus", "Teena Marie", "Patrice Rushen",
        "The Isley Brothers", "Curtis Mayfield", "Donny Hathaway",
        "Bill Withers", "Stevie Wonder", "Marvin Gaye", "Al Green",
        "The Temptations", "Four Tops", "The Supremes", "The O'Jays",
    ],

    "soul": [
        "Marvin Gaye", "Stevie Wonder", "Aretha Franklin", "Otis Redding",
        "Ray Charles", "Sam Cooke", "Al Green", "Curtis Mayfield",
        "Donny Hathaway", "Bill Withers", "James Brown", "Smokey Robinson",
        "Lauryn Hill", "Erykah Badu", "D'Angelo", "Jill Scott",
        "Leon Bridges", "Michael Kiwanuka", "Anderson Paak", "Gabriel Garzon-Montano",
        "Solange", "Janelle Monáe", "The Internet", "Mereba",
        "Cleo Sol", "Sault", "Lianne La Havas", "Corinne Bailey Rae",
        "Amy Winehouse", "Duffy", "Adele", "Joss Stone",
        "Alicia Keys", "John Legend", "India.Arie", "Musiq Soulchild",
        "Anthony Hamilton", "Raheem DeVaughn", "Jaheim", "Lyfe Jennings",
        "Glenn Lewis", "Maxwell", "Kem", "Ledisi",
        "Leela James", "Goapele", "Lalah Hathaway", "Meshell Ndegeocello",
        "Sharon Jones", "Charles Bradley", "Lee Fields", "Curtis Harding",
        "St. Paul and The Broken Bones", "Nathaniel Rateliff",
        "Alabama Shakes", "Brittany Howard", "Black Pumas",
        "Durand Jones & The Indications", "The Dip", "The Suffers",
        "Mayer Hawthorne", "Allen Stone", "Jesse Boykins III",
        "Abraham Alexander", "Son Little", "Benjamin Booker",
        "Percy Sledge", "Wilson Pickett", "Sam & Dave", "Booker T. & the M.G.'s",
    ],

    "k_pop": [
        "BTS", "BLACKPINK", "TWICE", "Stray Kids",
        "SEVENTEEN", "TOMORROW X TOGETHER", "NCT 127", "EXO",
        "Red Velvet", "aespa", "IVE", "NewJeans",
        "LE SSERAFIM", "ATEEZ", "ITZY", "ENHYPEN",
        "G-DRAGON", "BIGBANG", "IU", "PSY",
        "Girls' Generation", "SHINee", "Super Junior", "TVXQ",
        "2NE1", "Wonder Girls", "Miss A", "f(x)",
        "MONSTA X", "GOT7", "WINNER", "iKON",
        "MAMAMOO", "GFRIEND", "Apink", "AOA",
        "EXID", "SISTAR", "Girl's Day", "4Minute",
        "HyunA", "CL", "Sunmi", "Chungha",
        "Taeyeon", "BoA", "Zico", "DEAN",
        "Crush", "DPR LIVE", "pH-1", "Jay Park",
        "Loco", "Gray", "Simon Dominic", "The Quiett",
        "Epik High", "Dynamic Duo", "BewhY", "Changmo",
        "AKMU", "Bolbbalgan4", "10cm", "Standing Egg",
        "DAY6", "N.Flying", "CNBLUE", "FTISLAND",
        "NCT DREAM", "WayV", "Kep1er", "ZEROBASEONE",
    ],

    # ═══════════════════════════════════════════════════════════════════
    # NICHE GENRES (30-50 artists each)
    # ═══════════════════════════════════════════════════════════════════

    "house": [
        "Daft Punk", "Disclosure", "Gorgon City", "Chris Lake",
        "Dom Dolla", "John Summit", "Green Velvet", "MK",
        "CamelPhat", "Solardo", "Claptone", "Hot Since 82",
        "Guy Gerber", "Jamie Jones", "Dennis Ferrer", "Kerri Chandler",
        "Moodymann", "Theo Parrish", "Andrés", "Kyle Hall",
        "Larry Heard", "Marshall Jefferson", "Frankie Knuckles", "Ron Hardy",
        "Derrick Carter", "Mark Farina", "Doc Martin", "DJ Sneak",
        "Armand Van Helden", "Roger Sanchez", "Erick Morillo",
        "Bob Sinclar", "David Morales", "Todd Terry", "Louie Vega",
        "Kenny Dope", "Masters at Work", "Mood II Swing", "Sandy Rivera",
        "Kings of Tomorrow", "Duke Dumont", "Secondcity", "Oliver Heldens",
        "Tchami", "Malaa", "Hannah Wants", "Low Steppa",
        "Sonny Fodera", "Route 94", "Huxley", "Shadow Child",
    ],

    "techno": [
        "Carl Cox", "Jeff Mills", "Richie Hawtin", "Adam Beyer",
        "Amelie Lens", "Charlotte de Witte", "Boris Brejcha",
        "Tale of Us", "Nina Kraviz", "Ben Klock", "Maceo Plex",
        "Dixon", "Solomun", "Âme", "Marcel Dettmann",
        "Len Faki", "DVS1", "Oscar Mulero", "Regis",
        "Surgeon", "Ancient Methods", "Blawan", "Karenn",
        "Paula Temple", "Rebekah", "Perc", "Ansome",
        "Robert Hood", "Underground Resistance", "Kevin Saunderson",
        "Juan Atkins", "Derrick May", "Blake Baxter", "Eddie Fowlkes",
        "Drexciya", "Dopplereffekt", "Arpanet", "The Advent",
        "Chris Liebing", "Speedy J", "Monika Kruse", "Sven Väth",
        "Joseph Capriati", "Marco Carola", "Loco Dice", "Paco Osuna",
        "Stacey Pullen", "John Digweed", "Sasha", "Nick Warren",
    ],

    "ambient": [
        "Brian Eno", "Aphex Twin", "Boards of Canada", "Stars of the Lid",
        "A Winged Victory for the Sullen", "Hammock", "Eluvium",
        "Loscil", "William Basinski", "Tim Hecker", "Grouper",
        "Biosphere", "Julianna Barwick", "Helios", "Jon Hopkins",
        "Sigur Rós", "Jónsi", "Múm", "Amiina",
        "Harold Budd", "Robin Guthrie", "Liz Harris", "Hiroshi Yoshimura",
        "Satoshi Ashikawa", "Midori Takada", "Ryuichi Sakamoto",
        "Alva Noto", "Fennesz", "Oval", "Pan American",
        "Gas", "Wolfgang Voigt", "Bing & Ruth", "Max Richter",
        "Nils Frahm", "Ólafur Arnalds", "Christina Vantzou",
        "Library Tapes", "Goldmund", "Dustin O'Halloran", "Jóhann Jóhannsson",
        "Sarah Davachi", "Kali Malone", "Ellen Arkbro", "Caterina Barbieri",
        "Kaitlyn Aurelia Smith", "Emily A. Sprague", "Mary Lattimore",
    ],

    "folk": [
        "Bob Dylan", "Joni Mitchell", "Simon & Garfunkel", "Leonard Cohen",
        "James Taylor", "Cat Stevens", "Nick Drake", "Iron & Wine",
        "The Lumineers", "Mumford & Sons", "Hozier", "Noah Kahan",
        "Caamp", "Gregory Alan Isakov", "Donovan", "Crosby Stills Nash",
        "Vance Joy", "Of Monsters and Men", "Edward Sharpe and the Magnetic Zeros",
        "The Head and the Heart", "The Avett Brothers", "Lord Huron",
        "Fleet Foxes", "Bon Iver", "Sufjan Stevens", "Iron & Wine",
        "Damien Rice", "Glen Hansard", "The Swell Season", "Ben Howard",
        "Nick Mulvey", "José González", "Tallest Man on Earth",
        "Laura Marling", "First Aid Kit", "Daughter", "Birdy",
        "The Paper Kites", "Angus & Julia Stone", "The Staves",
        "Milk Carton Kids", "Mandolin Orange", "Watchhouse",
        "Shakey Graves", "Colter Wall", "Tyler Childers", "Jason Isbell",
        "Sturgill Simpson", "Chris Stapleton", "Zac Brown Band",
        "Punch Brothers", "Chris Thile", "Nickel Creek", "Gillian Welch",
        "Alison Krauss", "Emmylou Harris", "John Prine", "Townes Van Zandt",
    ],

    "punk": [
        "Green Day", "Ramones", "The Clash", "Blink-182",
        "Sex Pistols", "The Offspring", "Sum 41", "Rancid",
        "Bad Religion", "NOFX", "Rise Against", "Paramore",
        "My Chemical Romance", "Fall Out Boy", "Pierce the Veil",
        "A Day to Remember", "Good Charlotte", "Simple Plan",
        "New Found Glory", "The Starting Line", "Taking Back Sunday",
        "Brand New", "Jimmy Eat World", "Alkaline Trio",
        "Social Distortion", "Pennywise", "Strung Out", "Lagwagon",
        "No Use for a Name", "Face to Face", "Descendents", "ALL",
        "Hüsker Dü", "Minutemen", "Black Flag", "Dead Kennedys",
        "Circle Jerks", "Bad Brains", "Minor Threat", "Fugazi",
        "The Misfits", "Danzig", "Samhain", "AFI",
        "Against Me!", "Anti-Flag", "Propagandhi", "Strike Anywhere",
        "The Bouncing Souls", "Less Than Jake", "Reel Big Fish",
        "Streetlight Manifesto", "Goldfinger", "Suicide Machines",
    ],

    "alternative": [
        "Radiohead", "Nine Inch Nails", "The Smashing Pumpkins", "Beck",
        "Björk", "Thom Yorke", "St. Vincent", "The War on Drugs",
        "King Gizzard", "Fontaines D.C.", "IDLES", "Black Country New Road",
        "Wet Leg", "Alvvays", "Car Seat Headrest", "Courtney Barnett",
        "Pavement", "Sonic Youth", "PJ Harvey", "Portishead",
        "Massive Attack", "Tricky", "Morcheeba", "Sneaker Pimps",
        "Talking Heads", "David Byrne", "Brian Eno", "Robert Fripp",
        "Siouxsie and the Banshees", "Echo & the Bunnymen", "The Jesus and Mary Chain",
        "My Bloody Valentine", "Slowdive", "Ride", "Lush",
        "Cocteau Twins", "Dead Can Dance", "This Mortal Coil",
        "The Flaming Lips", "Spiritualized", "Spacemen 3", "Primal Scream",
        "Tame Impala", "Mac DeMarco", "Unknown Mortal Orchestra",
        "Chairlift", "Sylvan Esso", "Polica", "Little Dragon",
    ],

    "drum_and_bass": [
        "Pendulum", "Chase & Status", "Sub Focus", "Netsky",
        "High Contrast", "Wilkinson", "Andy C", "Noisia",
        "Dimension", "Metrik", "Sigma", "Hybrid Minds",
        "Camo & Krooked", "LTJ Bukem", "Goldie", "Roni Size",
        "London Elektricity", "Danny Byrd", "Logistics", "Nu:Tone",
        "Brookes Brothers", "Fred V & Grafix", "Keeno", "Whiney",
        "Etherwood", "Technimatic", "Lenzman", "LSB",
        "Calibre", "dBridge", "Commix", "Alix Perez",
        "SpectraSoul", "Ivy Lab", "Halogenix", "Ulterior Motive",
        "Break", "DLR", "Total Science", "Digital & Spirit",
        "Ed Rush & Optical", "Trace", "Fierce", "Dom & Roland",
        "Bad Company", "Fresh", "Adam F", "Macky Gee",
        "Turno", "Bou", "Kanine", "K Motionz",
    ],

    "lo_fi": [
        "Nujabes", "J Dilla", "Shlohmo", "Knxwledge",
        "Flying Lotus", "Teebs", "Tokimonsta", "Quickly Quickly",
        "Odie", "Samsa", "Atlas", "Potsu",
        "Jinsang", "Idealism", "Eevee", "Wun Two",
        "Saib", "Aso", "Flamingosis", "Tomppabeats",
        "Elijah Who", "Mommy", "Philanthrope", "Psalm Trees",
        "Kupla", "Sleepdealer", "A L E X", "Kudasaibeats",
        "Birocratic", "Enzalla", "Tenno", "Sugi.wa",
        "City Girl", "Alicks", "In Love With a Ghost", "Mikel",
        "Mono", "Kavv", "Jhfly", "Bcalm",
        "Strehlow", "Glue70", "George", "The Deli",
        "Brock Berrigan", "Bonus Points", "B-Side", "L'indécis",
        "Chief.", "Rook1e", "Kiefer", "Mndsgn",
        "Ohbliv", "Tuamie", "Ahwlee", "Dibia$E",
    ],

    "world": [
        "Angélique Kidjo", "Ali Farka Touré", "Buena Vista Social Club",
        "Tinariwen", "Fela Kuti", "King Sunny Adé", "Ladysmith Black Mambazo",
        "Youssou N'Dour", "Cesária Évora", "Salif Keïta", "Ravi Shankar",
        "Anoushka Shankar", "Bombino", "Mdou Moctar", "Ibeyi",
        "Baaba Maal", "Amadou & Mariam", "Oumou Sangaré", "Bebel Gilberto",
        "Paco de Lucía", "Buika", "Concha Buika", "Yasmin Levy",
        "Ojos de Brujo", "Macaco", "Amparanoia", "Manu Chao",
        "Goran Bregović", "Emir Kusturica", "Fanfare Ciocărlia",
        "Taraf de Haïdouks", "Kocani Orkestar", "Mahmoud Ahmed",
        "Mulatu Astatke", "Getatchew Mekurya", "Hailu Mergia",
        "Orchestra Baobab", "Touré Kunda", "Ismaël Lô",
        "Habib Koité", "Rokia Traoré", "Fatoumata Diawara",
        "Angelique Kidjo", "Dobet Gnahoré", "Ladysmith Black Mambazo",
        "Hugh Masekela", "Miriam Makeba", "Abdullah Ibrahim",
        "Mongo Santamaría", "Tito Puente", "Celia Cruz", "Rubén Blades",
    ],

    "singer_songwriter": [
        "Ed Sheeran", "Taylor Swift", "John Mayer", "Norah Jones",
        "Adele", "Tracy Chapman", "Carole King", "Bruce Springsteen",
        "Van Morrison", "Paul Simon", "Joni Mitchell", "Neil Young",
        "Jason Mraz", "Brandi Carlile", "Vance Joy", "Ray LaMontagne",
        "Regina Spektor", "Ben Howard", "Dallas Green", "Damien Rice",
        "Glen Hansard", "Lisa Hannigan", "Fionn Regan", "James Vincent McMorrow",
        "Jamie Cullum", "James Blunt", "Daniel Powter", "David Gray",
        "Passenger", "James Bay", "George Ezra", "Tom Odell",
        "Jack Johnson", "Ben Harper", "Xavier Rudd", "Michael Franti",
        "Bob Marley", "Jeff Buckley", "Rufus Wainwright", "Martha Wainwright",
        "Feist", "Cat Power", "Joan Baez", "Judy Collins",
        "Kris Kristofferson", "Willie Nelson", "Johnny Cash", "Bob Dylan",
        "Leonard Cohen", "Tom Waits", "Nick Cave", "Warren Zevon",
        "Jackson Browne", "James Taylor", "Jim Croce", "Don McLean",
        "José González", "Sufjan Stevens", "Bon Iver", "Iron & Wine",
        "Bright Eyes", "Conor Oberst", "Daughter", "Julien Baker",
    ],
}

# ── Brazilian artists (200+ additional) ───────────────────────────────

BRAZILIAN_ARTISTS_MASSIVE: dict[str, list[str]] = {
    "sertanejo": [
        "Jorge & Mateus", "Henrique & Juliano", "Marília Mendonça",
        "Gusttavo Lima", "Luan Santana", "Zé Neto & Cristiano",
        "Maiara & Maraisa", "Matheus & Kauan", "Simone & Simaria",
        "Fernando & Sorocaba", "Israel & Rodolffo", "Hugo & Guilherme",
        "Victor & Leo", "César Menotti & Fabiano", "Bruno & Marrone",
        "Edson & Hudson", "Chitãozinho & Xororó", "Leandro & Leonardo",
        "Zezé Di Camargo & Luciano", "Daniel", "Paula Fernandes",
        "Cristiano Araújo", "Naiara Azevedo", "Marília Tavares",
        "João Bosco & Vinícius", "Michel Teló", "Munhoz & Mariano",
        "Cleber & Cauan", "Thaeme & Thiago", "Lucas Lucco",
    ],
    "mpb": [
        "Caetano Veloso", "Gilberto Gil", "Chico Buarque", "Milton Nascimento",
        "Elis Regina", "Marisa Monte", "Djavan", "Nando Reis",
        "Vanessa da Mata", "Zeca Baleiro", "Lenine", "Céu",
        "Adriana Calcanhotto", "Gal Costa", "Belchior", "Tom Jobim",
        "Vinícius de Moraes", "Toquinho", "Baden Powell", "João Gilberto",
        "Astrud Gilberto", "Bebel Gilberto", "Jorge Ben Jor", "Tim Maia",
        "Cassia Eller", "Ana Carolina", "Seu Jorge", "Roberta Sá",
        "Maria Gadú", "Tiago Iorc", "AnaVitória", "Tulipa Ruiz",
    ],
    "samba": [
        "Zeca Pagodinho", "Beth Carvalho", "Martinho da Vila", "Alcione",
        "Jorge Aragão", "Arlindo Cruz", "Diogo Nogueira", "Dona Ivone Lara",
        "Cartola", "Noel Rosa", "Clara Nunes", "Fundo de Quintal",
        "Paulinho da Viola", "Grupo Revelação", "Exaltasamba", "Nelson Sargento",
        "Adoniran Barbosa", "Jamela", "Teresa Cristina", "Roberta Sá",
        "Maria Rita", "Monarco", "Agepê", "Dudu Nobre",
        "Leci Brandão", "Jovelina Pérola Negra", "Candeia",
        "Wilson Moreira", "Nelson Cavaquinho", "Guilherme de Brito",
    ],
    "pagode": [
        "Thiaguinho", "Fundo de Quintal", "Raça Negra", "Soweto",
        "Turma do Pagode", "Sorriso Maroto", "Péricles", "Exaltasamba",
        "Pique Novo", "Ferrugem", "Dilsinho", "Menos é Mais",
        "Grupo Revelação", "Os Travessos", "Jeito Moleque", "Belo",
        "Alexandre Pires", "Molejo", "Art Popular", "Só Pra Contrariar",
        "Inimigos da HP", "Karametade", "Sem Compromisso", "Katinguelê",
        "Grupo Raça Negra", "Grupo Sensação", "Nosso Sentimento", "Grupo Clareou",
        "Samba Livre", "Grupo Pixote", "Tá Na Mente", "Gustavo Lins",
    ],
    "forro": [
        "Wesley Safadão", "Aviões do Forró", "Calcinha Preta", "Banda Magníficos",
        "Mastruz com Leite", "Limão com Mel", "Elba Ramalho", "Alceu Valença",
        "Dominguinhos", "Dorgival Dantas", "Falamansa", "Bicho de Pé",
        "Baião de 2", "Cavaleiros do Forró", "Solange Almeida",
        "Luiz Gonzaga", "Jackson do Pandeiro", "Marinês", "Genival Lacerda",
        "Zé Ramalho", "Geraldo Azevedo", "Flávio José", "Petrúcio Amorim",
        "Maciel Melo", "Santanna", "Alcymar Monteiro", "Eliane",
        "Targino Gondim", "Mestre Ambrósio", "Cascabulho", "Forróçacana",
    ],
    "funk_br": [
        "Anitta", "Kevin O Chris", "MC Livinho", "MC Kevinho",
        "Ludmilla", "KondZilla", "MC Davi", "Pabllo Vittar",
        "MC Loma", "MC Rebecca", "Lexa", "Valesca Popozuda",
        "MC Don Juan", "Gloria Groove", "MC G15", "Pedro Sampaio",
        "Luisa Sonza", "Pocah", "MC Zaac", "MC Fioti",
        "MC WM", "MC Lan", "MC MM", "MC Jhowzinho e Kadinho",
        "MC Kekel", "MC Neguinho do Kaxeta", "MC Bola", "MC Marcinho",
        "MC Sapão", "Bonde do Tigrão", "Tati Quebra-Barraco", "Gaiola das Popozudas",
    ],
    "gospel_br": [
        "Fernandinho", "Aline Barros", "Diante do Trono", "Gabriela Rocha",
        "André Valadão", "Isaias Saad", "Ministério Zoe", "Cassiane",
        "Damares", "Anderson Freire", "Bruna Karla", "Nívea Soares",
        "Ana Paula Valadão", "Paulo César Baruk", "Gabriel Guedes",
        "Fred Arrais", "Laura Souguellis", "Morada", "Fhop Music",
        "Casa Worship", "Vale Music", "DNA Music", "Julliany Souza",
        "Léo Brandão", "Felipe Vilela", "Sued Silva", "Vitória Souza",
        "Eliane Silva", "Lauriete", "Shirley Carvalhaes", "Midian Lima",
    ],
    "rock_br": [
        "Legião Urbana", "Titãs", "Paralamas do Sucesso", "Cazuza",
        "Barão Vermelho", "Capital Inicial", "Skank", "Charlie Brown Jr.",
        "Nação Zumbi", "O Rappa", "Os Mutantes", "Engenheiros do Hawaii",
        "Raimundos", "Planet Hemp", "Supercombo", "NX Zero",
        "CPM 22", "Detonautas", "Jota Quest", "Biquini Cavadão",
        "Ultraje a Rigor", "Ira!", "Inocentes", "Plebe Rude",
        "Dead Fish", "Ratos de Porão", "Garotos Podres", "Cólera",
        "Sepultura", "Angra", "Viper", "Shaaman",
    ],
    "rap_br": [
        "Racionais MC's", "Sabotage", "Criolo", "Haikaiss",
        "Hungria Hip Hop", "Projota", "Filipe Ret", "Kant",
        "Djonga", "BK'", "Baco Exu do Blues", "Tasha & Tracie",
        "Major RD", "Xamã", "Froid", "Sant",
        "Mano Brown", "Emicida", "Rashid", "Pineapple Storm",
        "Costa Gold", "Oriente", "ConeCrewDiretoria", "Sain",
        "Matuê", "Teto", "WiU", "MC Cabelinho",
        "MC Poze do Rodo", "Oruam", "Chefin", "Borges",
    ],
}

# ── Combine all for total count ───────────────────────────────────────

ALL_ARTISTS: list[str] = []
for _genre, artists in MASSIVE_SEED.items():
    ALL_ARTISTS.extend(artists)
for _genre, artists in BRAZILIAN_ARTISTS_MASSIVE.items():
    ALL_ARTISTS.extend(artists)

# Deduplicate by name
ALL_ARTISTS = list(dict.fromkeys(ALL_ARTISTS))

TOTAL_ARTISTS = len(ALL_ARTISTS)
