"""
Seed catalog data: 200+ top global artists, Brazilian artists,
trending tracks, and genre-specific search queries for batch ingestion.
"""

TOP_ARTISTS: dict[str, list[str]] = {
    "pop": [
        "Taylor Swift", "Ed Sheeran", "Bruno Mars", "Ariana Grande",
        "Dua Lipa", "Harry Styles", "Billie Eilish", "Justin Bieber",
        "Lady Gaga", "The Weeknd", "SZA", "Olivia Rodrigo",
        "Miley Cyrus", "Shawn Mendes", "Katy Perry", "Rihanna",
        "Sam Smith", "Sia", "Charlie Puth", "Selena Gomez",
        "Camila Cabello", "Demi Lovato", "Halsey", "Lizzo",
        "Doja Cat", "Pink", "Maroon 5", "Adele",
        "Lana Del Rey", "Sabrina Carpenter", "Chappell Roan", "Tate McRae",
    ],
    "rock": [
        "Queen", "Nirvana", "Led Zeppelin", "AC/DC",
        "Pink Floyd", "Foo Fighters", "The Beatles", "Red Hot Chili Peppers",
        "U2", "Green Day", "Linkin Park", "Coldplay",
        "Arctic Monkeys", "Radiohead", "The Killers", "Muse",
        "The Strokes", "Oasis", "Weezer", "Pearl Jam",
        "Bon Jovi", "Journey", "Guns N' Roses", "Metallica",
        "Aerosmith", "The Rolling Stones", "The Who", "Eagles",
    ],
    "hip_hop": [
        "Kendrick Lamar", "Drake", "J. Cole", "Travis Scott",
        "Kanye West", "Eminem", "Jay-Z", "Lil Wayne",
        "Nicki Minaj", "Cardi B", "Megan Thee Stallion", "Tyler the Creator",
        "21 Savage", "Future", "Post Malone", "Kid Cudi",
        "A$AP Rocky", "Mac Miller", "Lil Baby", "Jack Harlow",
        "Metro Boomin", "Playboi Carti", "Juice WRLD", "Pop Smoke",
    ],
    "r_and_b": [
        "Beyoncé", "Frank Ocean", "Usher", "Chris Brown",
        "Alicia Keys", "John Legend", "Daniel Caesar", "H.E.R.",
        "Summer Walker", "Jhené Aiko", "Bryson Tiller", "6LACK",
        "Toni Braxton", "Mariah Carey", "Whitney Houston", "Luther Vandross",
        "Miguel", "Snoh Aalegra", "Brent Faiyaz", "PartyNextDoor",
    ],
    "country": [
        "Luke Combs", "Morgan Wallen", "Chris Stapleton", "Zach Bryan",
        "Kacey Musgraves", "Carrie Underwood", "Tim McGraw", "Blake Shelton",
        "Keith Urban", "Dolly Parton", "Willie Nelson", "Johnny Cash",
        "Garth Brooks", "George Strait", "Carly Pearce", "Dan + Shay",
        "Thomas Rhett", "Kane Brown", "Lainey Wilson", "Bailey Zimmerman",
    ],
    "electronic": [
        "Calvin Harris", "David Guetta", "Martin Garrix", "Skrillex",
        "Tiësto", "Deadmau5", "Avicii", "Zedd",
        "Disclosure", "ODESZA", "Flume", "Marshmello",
        "Illenium", "Kygo", "Swedish House Mafia", "Diplo",
        "The Chainsmokers", "Rufus Du Sol", "Jamie xx", "Four Tet",
    ],
    "jazz": [
        "Miles Davis", "John Coltrane", "Billie Holiday", "Duke Ellington",
        "Herbie Hancock", "Thelonious Monk", "Charlie Parker", "Ella Fitzgerald",
        "Dave Brubeck", "Louis Armstrong", "Oscar Peterson", "Chet Baker",
        "Kamasi Washington", "Robert Glasper", "Esperanza Spalding", "Charles Mingus",
        "Nina Simone", "Sonny Rollins", "Wayne Shorter", "Pat Metheny",
    ],
    "classical": [
        "Ludovico Einaudi", "Max Richter", "Olafur Arnalds", "Nils Frahm",
        "Johann Sebastian Bach", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart",
        "Frédéric Chopin", "Pyotr Ilyich Tchaikovsky", "Claude Debussy",
        "Antonio Vivaldi", "Yo-Yo Ma", "André Rieu", "Lang Lang",
        "John Williams", "Hans Zimmer", "Alexandre Desplat", "Einaudi",
    ],
    "blues": [
        "B.B. King", "Muddy Waters", "Robert Johnson", "John Lee Hooker",
        "Buddy Guy", "Stevie Ray Vaughan", "Eric Clapton", "Howlin' Wolf",
        "Gary Clark Jr.", "Joe Bonamassa", "Taj Mahal", "Albert King",
        "Etta James", "Lead Belly", "Keb' Mo'", "Susan Tedeschi",
    ],
    "metal": [
        "Metallica", "Iron Maiden", "Black Sabbath", "Slayer",
        "Megadeth", "Pantera", "Tool", "System of a Down",
        "Slipknot", "Avenged Sevenfold", "Rammstein", "Disturbed",
        "Lamb of God", "Mastodon", "Gojira", "Opeth",
        "Korn", "Deftones", "Bring Me The Horizon", "Ghost",
    ],
    "punk": [
        "Green Day", "Ramones", "The Clash", "Blink-182",
        "Sex Pistols", "The Offspring", "Sum 41", "Rancid",
        "Bad Religion", "NOFX", "Rise Against", "Paramore",
        "My Chemical Romance", "Fall Out Boy", "Pierce the Veil",
        "A Day to Remember",
    ],
    "indie": [
        "Mac DeMarco", "Tame Impala", "Vampire Weekend", "Fleet Foxes",
        "Bon Iver", "Beach House", "Phoenix", "MGMT",
        "Arcade Fire", "The xx", "Alt-J", "Glass Animals",
        "Boygenius", "Japanese Breakfast", "Big Thief", "Phoebe Bridgers",
        "Sufjan Stevens", "The National", "Modest Mouse", "Death Cab for Cutie",
    ],
    "folk": [
        "Bob Dylan", "Joni Mitchell", "Simon & Garfunkel", "Leonard Cohen",
        "James Taylor", "Cat Stevens", "Nick Drake", "Iron & Wine",
        "The Lumineers", "Mumford & Sons", "Hozier", "Noah Kahan",
        "Caamp", "Gregory Alan Isakov", "Donovan", "Crosby Stills Nash",
    ],
    "reggae": [
        "Bob Marley", "Peter Tosh", "Jimmy Cliff", "Toots and the Maytals",
        "Steel Pulse", "Damian Marley", "UB40", "Lee Scratch Perry",
        "Burning Spear", "Ziggy Marley", "Dennis Brown", "Gregory Isaacs",
        "Buju Banton", "Sizzla", "Chronixx", "Protoje",
    ],
    "latin": [
        "Bad Bunny", "Shakira", "J Balvin", "Rosalía",
        "Karol G", "Daddy Yankee", "Ozuna", "Rauw Alejandro",
        "Maluma", "Anitta", "Luis Fonsi", "Marc Anthony",
        "Romeo Santos", "Feid", "Nicky Jam", "Manuel Turizo",
        "Becky G", "Enrique Iglesias", "Sech", "Luis Miguel",
    ],
    "k_pop": [
        "BTS", "BLACKPINK", "TWICE", "Stray Kids",
        "SEVENTEEN", "TOMORROW X TOGETHER", "NCT 127", "EXO",
        "Red Velvet", "aespa", "IVE", "NewJeans",
        "LE SSERAFIM", "ATEEZ", "ITZY", "ENHYPEN",
        "G-DRAGON", "BIGBANG", "IU", "PSY",
    ],
    "soul": [
        "Marvin Gaye", "Stevie Wonder", "Aretha Franklin", "Otis Redding",
        "Ray Charles", "Sam Cooke", "Al Green", "Curtis Mayfield",
        "Donny Hathaway", "Bill Withers", "James Brown", "Smokey Robinson",
        "Lauryn Hill", "Erykah Badu", "D'Angelo", "Jill Scott",
        "Leon Bridges", "Michael Kiwanuka", "Anderson Paak", "Gabriel Garzon-Montano",
    ],
    "funk": [
        "James Brown", "George Clinton", "Parliament", "Funkadelic",
        "Sly and the Family Stone", "Earth Wind and Fire", "Tower of Power",
        "Prince", "Rick James", "Bootsy Collins", "Cameo",
        "Graham Central Station", "The Meters", "Vulfpeck", "Khruangbin",
        "Thundercat", "Tom Misch", "Jamiroquai", "Cory Wong",
    ],
    "gospel": [
        "Kirk Franklin", "CeCe Winans", "Donnie McClurkin", "Tasha Cobbs",
        "Marvin Sapp", "Tamela Mann", "Fred Hammond", "Shirley Caesar",
        "Jonathan McReynolds", "Kierra Sheard", "Maurette Brown Clark",
        "Yolanda Adams", "Lauren Daigle", "Elevation Worship",
        "Hillsong United", "Chris Tomlin", "Maverick City Music", "Bethel Music",
    ],
    "alternative": [
        "Radiohead", "Nine Inch Nails", "The Smashing Pumpkins", "Beck",
        "Björk", "Thom Yorke", "St. Vincent", "The War on Drugs",
        "King Gizzard", "Fontaines D.C.", "IDLES", "Black Country New Road",
        "Wet Leg", "Alvvays", "Car Seat Headrest", "Courtney Barnett",
        "Pavement", "Sonic Youth", "PJ Harvey", "Portishead",
    ],
    "singer_songwriter": [
        "Ed Sheeran", "Taylor Swift", "John Mayer", "Norah Jones",
        "Adele", "Tracy Chapman", "Carole King", "Bruce Springsteen",
        "Van Morrison", "Paul Simon", "Joni Mitchell", "Neil Young",
        "Jason Mraz", "Brandi Carlile", "Vance Joy", "Ray LaMontagne",
        "Regina Spektor", "Ben Howard", "Dallas Green", "Damien Rice",
    ],
    "world": [
        "Angélique Kidjo", "Ali Farka Touré", "Buena Vista Social Club",
        "Tinariwen", "Fela Kuti", "King Sunny Adé", "Ladysmith Black Mambazo",
        "Youssou N'Dour", "Cesária Évora", "Salif Keïta", "Ravi Shankar",
        "Anoushka Shankar", "Bombino", "Mdou Moctar", "Ibeyi",
        "Baaba Maal", "Amadou & Mariam", "Oumou Sangaré", "Bebel Gilberto",
    ],
    "ambient": [
        "Brian Eno", "Aphex Twin", "Boards of Canada", "Stars of the Lid",
        "A Winged Victory for the Sullen", "Hammock", "Eluvium",
        "Loscil", "William Basinski", "Tim Hecker", "Grouper",
        "Biosphere", "Julianna Barwick", "Helios", "Jon Hopkins",
    ],
    "house": [
        "Daft Punk", "Disclosure", "Gorgon City", "Chris Lake",
        "Dom Dolla", "John Summit", "Green Velvet", "MK",
        "CamelPhat", "Solardo", "Claptone", "Hot Since 82",
        "Guy Gerber", "Jamie Jones", "Dennis Ferrer", "Kerri Chandler",
    ],
    "techno": [
        "Carl Cox", "Jeff Mills", "Richie Hawtin", "Adam Beyer",
        "Amelie Lens", "Charlotte de Witte", "Boris Brejcha",
        "Tale of Us", "Nina Kraviz", "Ben Klock", "Maceo Plex",
        "Dixon", "Solomun", "Âme", "Marcel Dettmann",
    ],
    "drum_and_bass": [
        "Pendulum", "Chase & Status", "Sub Focus", "Netsky",
        "High Contrast", "Wilkinson", "Andy C", "Noisia",
        "Dimension", "Metrik", "Sigma", "Hybrid Minds",
        "Camo & Krooked", "LTJ Bukem", "Goldie", "Roni Size",
    ],
    "lo_fi": [
        "Nujabes", "J Dilla", "Shlohmo", "Knxwledge",
        "Flying Lotus", "Teebs", "Tokimonsta", "Quickly Quickly",
        "Odie", "Samsa", "Atlas", "Potsu",
        "Jinsang", "Idealism", "Eevee", "Wun Two",
    ],
}

BRAZILIAN_ARTISTS: dict[str, list[str]] = {
    "sertanejo": [
        "Jorge & Mateus", "Henrique & Juliano", "Marília Mendonça",
        "Gusttavo Lima", "Luan Santana", "Zé Neto & Cristiano",
        "Maiara & Maraisa", "Matheus & Kauan", "Simone & Simaria",
        "Fernando & Sorocaba", "Israel & Rodolffo", "Hugo & Guilherme",
        "Victor & Leo", "César Menotti & Fabiano", "Bruno & Marrone",
    ],
    "mpb": [
        "Caetano Veloso", "Gilberto Gil", "Chico Buarque", "Milton Nascimento",
        "Elis Regina", "Marisa Monte", "Djavan", "Nando Reis",
        "Vanessa da Mata", "Zeca Baleiro", "Lenine", "Céu",
        "Adriana Calcanhotto", "Gal Costa", "Belchior", "Tom Jobim",
    ],
    "samba": [
        "Zeca Pagodinho", "Beth Carvalho", "Martinho da Vila", "Alcione",
        "Jorge Aragão", "Arlindo Cruz", "Diogo Nogueira", "Dona Ivone Lara",
        "Cartola", "Noel Rosa", "Clara Nunes", "Fundo de Quintal",
        "Paulinho da Viola", "Grupo Revelação", "Exaltasamba", "Nelson Sargento",
    ],
    "pagode": [
        "Thiaguinho", "Fundo de Quintal", "Raça Negra", "Soweto",
        "Turma do Pagode", "Sorriso Maroto", "Péricles", "Exaltasamba",
        "Pique Novo", "Ferrugem", "Dilsinho", "Menos é Mais",
        "Grupo Revelação", "Os Travessos", "Jeito Moleque", "Belo",
    ],
    "forro": [
        "Wesley Safadão", "Aviões do Forró", "Calcinha Preta", "Banda Magníficos",
        "Mastruz com Leite", "Limão com Mel", "Elba Ramalho", "Alceu Valença",
        "Dominguinhos", "Dorgival Dantas", "Falamansa", "Bicho de Pé",
        "Baião de 2", "Cavaleiros do Forró", "Solange Almeida",
    ],
    "funk_br": [
        "Anitta", "Kevin O Chris", "MC Livinho", "MC Kevinho",
        "Ludmilla", "KondZilla", "MC Davi", "Pabllo Vittar",
        "MC Loma", "MC Rebecca", "Lexa", "Valesca Popozuda",
        "MC Don Juan", "Gloria Groove", "MC G15",
    ],
    "gospel_br": [
        "Fernandinho", "Aline Barros", "Diante do Trono", "Gabriela Rocha",
        "André Valadão", "Isaias Saad", "Ministério Zoe", "Cassiane",
        "Damares", "Anderson Freire", "Bruna Karla", "Nívea Soares",
        "Ana Paula Valadão", "Paulo César Baruk",
    ],
    "rock_br": [
        "Legião Urbana", "Titãs", "Paralamas do Sucesso", "Cazuza",
        "Barão Vermelho", "Capital Inicial", "Skank", "Charlie Brown Jr.",
        "Nação Zumbi", "O Rappa", "Os Mutantes", "Engenheiros do Hawaii",
        "Raimundos", "Planet Hemp", "Supercombo", "NX Zero",
    ],
    "rap_br": [
        "Racionais MC's", "Sabotage", "Criolo", "Haikaiss",
        "Hungria Hip Hop", "Projota", "Filipe Ret", "Kant",
        "Djonga", "BK'", "Baco Exu do Blues", "Tasha & Tracie",
        "Major RD", "Xamã", "Froid", "Sant",
    ],
}

TRENDING_TRACKS: list[str] = [
    "Cruel Summer Taylor Swift",
    "Blinding Lights The Weeknd",
    "Shape of You Ed Sheeran",
    "Flowers Miley Cyrus",
    "Anti-Hero Taylor Swift",
    "Vampire Olivia Rodrigo",
    "As It Was Harry Styles",
    "Bad Habits Ed Sheeran",
    "Stay The Kid LAROI",
    "Levitating Dua Lipa",
    "Save Your Tears The Weeknd",
    "Good 4 U Olivia Rodrigo",
    "Heat Waves Glass Animals",
    "Drivers License Olivia Rodrigo",
    "Montero Lil Nas X",
    "Peaches Justin Bieber",
    "Kiss Me More Doja Cat",
    "Positions Ariana Grande",
    "Watermelon Sugar Harry Styles",
    "Dance Monkey Tones And I",
    "Unholy Sam Smith",
    "About Damn Time Lizzo",
    "I Ain't Worried OneRepublic",
    "Running Up That Hill Kate Bush",
    "Cold Heart Elton John Dua Lipa",
    "Espresso Sabrina Carpenter",
    "Lose Control Teddy Swims",
    "Beautiful Things Benson Boone",
    "I Had Some Help Post Malone",
    "Not Like Us Kendrick Lamar",
    "Million Dollar Baby Tommy Richman",
    "BIRDS OF A FEATHER Billie Eilish",
    "Die With A Smile Lady Gaga Bruno Mars",
    "A Bar Song Tipsy Shaboozey",
    "Taste Sabrina Carpenter",
    "Austin Dasha",
    "Last Night Morgan Wallen",
    "Fast Car Luke Combs",
    "Rich Baby Daddy Drake",
    "Stick Season Noah Kahan",
    "If I Can Dream Elvis Presley",
    "My Love Mine All Mine Mitski",
    "Greedy Tate McRae",
    "Water Tyla",
    "Exes Tate McRae",
    "Strangers Kenya Grace",
    "Dance The Night Dua Lipa",
    "Calm Down Rema",
    "Seven Jung Kook",
    "Like Crazy Jimin",
    "Kill Bill SZA",
    "Flower Jisoo",
    "OMG NewJeans",
    "Ditto NewJeans",
    "Super Shy NewJeans",
    "Cupid Fifty Fifty",
    "Pink Venom BLACKPINK",
    "Take Two BTS",
    "Doja Central Cee",
    "Paint The Town Red Doja Cat",
    "First Person Shooter Drake",
    "IDGAF Drake Yeat",
    "Fukumean Gunna",
    "Search & Rescue Drake",
    "All My Life Lil Durk",
    "Princess Diana Ice Spice",
    "Chemical Post Malone",
    "Popular The Weeknd Madonna",
    "Meltdown Travis Scott",
    "FE!N Travis Scott",
    "Say Yes To Heaven Lana Del Rey",
    "Ella Baila Sola Eslabon Armado",
    "Queencard G-IDLE",
    "S-Class Stray Kids",
    "Super Seventeen",
    "Bouncy ATEEZ",
    "Spicy aespa",
    "Unforgiven LE SSERAFIM",
    "I AM IVE",
    "Sugar Rush Ride TXT",
    "Fighting BSS",
    "No More Dream BTS",
    "Money Lisa",
    "SOLO JENNIE",
    "On The Street J-Hope",
    "People Pt 2 Agust D",
    "Wild Flower RM",
    "Set Me Free Twice",
    "Moonlight Sunrise Twice",
    "Shoong Taeyang Lisa",
    "On the Ground Rosé",
    "Lalisa Lisa",
    "Gone Rosé",
    "Vibe Taeyang Jimin",
    "Smoke Sprite SoYoon RM",
    "Pink Venom BLACKPINK",
]

GENRE_SEED_QUERIES: dict[str, list[str]] = {
    "pop": ["pop hits 2024", "pop anthems", "pop ballads", "dance pop songs", "synth pop"],
    "rock": ["rock classics", "classic rock anthems", "alternative rock hits", "rock ballads", "garage rock"],
    "hip_hop": ["hip hop hits", "trap beats", "conscious rap", "old school hip hop", "southern rap"],
    "r_and_b": ["rnb slow jams", "neo soul", "contemporary rnb", "rnb hits", "quiet storm"],
    "country": ["country hits", "country pop", "outlaw country", "bro country", "country ballads"],
    "electronic": ["edm hits", "deep house", "future bass", "synthwave", "chill electronic"],
    "jazz": ["jazz standards", "cool jazz", "bebop classics", "smooth jazz", "jazz fusion"],
    "classical": ["classical masterpieces", "solo piano", "orchestral music", "opera arias", "string quartets"],
    "blues": ["electric blues", "delta blues", "chicago blues", "blues rock", "slow blues"],
    "metal": ["heavy metal", "death metal", "thrash metal", "power metal", "progressive metal"],
    "punk": ["pop punk", "hardcore punk", "ska punk", "punk rock", "post punk"],
    "indie": ["indie pop", "dream pop", "shoegaze", "bedroom pop", "indie folk"],
    "folk": ["folk rock", "americana", "indie folk", "traditional folk", "celtic folk"],
    "reggae": ["roots reggae", "dancehall", "reggae classics", "ska", "lovers rock"],
    "latin": ["reggaeton hits", "latin pop", "bachata", "salsa classics", "latin trap"],
    "k_pop": ["kpop hits", "korean rnb", "korean hip hop", "kpop ballads", "krock"],
    "soul": ["motown classics", "philadelphia soul", "modern soul", "southern soul", "blue-eyed soul"],
    "funk": ["p funk", "boogie funk", "disco funk", "g funk", "modern funk"],
    "gospel": ["gospel choir", "black gospel", "southern gospel", "worship music", "gospel hymns"],
    "alternative": ["alternative rock 90s", "post rock", "noise rock", "math rock", "art rock"],
    "singer_songwriter": ["acoustic covers", "singer songwriter", "folk acoustic", "storytelling songs", "country folk"],
    "world": ["afrobeat", "highlife", "bossa nova", "rai music", "fado"],
    "ambient": ["ambient music", "drone music", "soundscapes", "new age music", "meditation music"],
    "house": ["deep house", "tech house", "afro house", "progressive house", "funky house"],
    "techno": ["minimal techno", "melodic techno", "acid techno", "dub techno", "peak time techno"],
    "drum_and_bass": ["liquid dnb", "neurofunk", "jungle drum and bass", "dancefloor dnb", "intelligent dnb"],
    "lo_fi": ["lofi hip hop", "jazzhop", "chillhop", "study beats", "lofi house"],
}
